In [ ]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
!nvidia-smi


Sun Dec 29 19:12:56 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   44C    P8              12W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
torch.__version__

'2.5.1+cu121'

## Introduction to tensors

In [ ]:
first_tensor = torch.tensor(5)
first_tensor

tensor(5)

In [ ]:
first_tensor.ndim

0

In [ ]:
t2 = torch.tensor([1,2,3])
t2

tensor([1, 2, 3])

In [ ]:
t2.add(torch.tensor([1,2,3]))

tensor([2, 4, 6])

In [ ]:
t2.shape, t2.ndim, t2.dtype

(torch.Size([3]), 1, torch.int64)

In [ ]:
t3 = torch.tensor([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
t3

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
t3[0],t3[1],t3[2]

(tensor([1, 2, 3]), tensor([4, 5, 6]), tensor([7, 8, 9]))

In [ ]:
t3.shape, t3.ndim, t3.dtype

(torch.Size([3, 3]), 2, torch.int64)

In [ ]:
t3.diag()

tensor([1, 5, 9])

In [ ]:
t3.t()

tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

In [ ]:
t3.transpose(0,1)

tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

In [ ]:
t4 = torch.randn(3,3,3)
t4

tensor([[[ 1.0782,  0.6336,  0.4027],
         [ 0.3994,  0.7196, -0.2171],
         [-1.6673, -0.0961, -1.1533]],

        [[-0.3125,  0.2146, -1.2940],
         [-0.7830,  0.5406, -1.5510],
         [-0.1699, -0.5975,  0.2009]],

        [[-0.4487, -0.0146,  0.9079],
         [-0.9526,  0.3616, -0.0960],
         [ 0.5605, -0.5726,  0.0967]]])

In [ ]:
t4.shape , t4.ndim

(torch.Size([3, 3, 3]), 3)

In [ ]:
for i in range(0,t4.shape[0]): # looping throw every MATRIX
  print(f"For MATRIX {i+1}: ")
  for j in range(0,t4.shape[1]): # looping throw every vector in i'th MATRIX
    print(f"\tThe {j+1} Vector is : ", end="")
    print(t4[i][j])

For MATRIX 1: 
	The 1 Vector is : tensor([1.0782, 0.6336, 0.4027])
	The 2 Vector is : tensor([ 0.3994,  0.7196, -0.2171])
	The 3 Vector is : tensor([-1.6673, -0.0961, -1.1533])
For MATRIX 2: 
	The 1 Vector is : tensor([-0.3125,  0.2146, -1.2940])
	The 2 Vector is : tensor([-0.7830,  0.5406, -1.5510])
	The 3 Vector is : tensor([-0.1699, -0.5975,  0.2009])
For MATRIX 3: 
	The 1 Vector is : tensor([-0.4487, -0.0146,  0.9079])
	The 2 Vector is : tensor([-0.9526,  0.3616, -0.0960])
	The 3 Vector is : tensor([ 0.5605, -0.5726,  0.0967])


## Random tensors

Why Random tensors ?

Random tensors are the way neural networks learn, they start with tensors full of random numbers and then adjust the number based on the data.

`Start with Random tensors -> repeat: ( look at data -> update random numbers)`

In [ ]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.9590, 0.1246, 0.7662, 0.9226],
        [0.7695, 0.3338, 0.0091, 0.3301],
        [0.9678, 0.6335, 0.4806, 0.4346]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# Random tensor with similar shape to an image
random_image_tensor = torch.rand(size=(224,224,3)) # height, width, color channels (R,G,B)
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros and ones tensors

In [ ]:
zeros = torch.zeros(size=(3,3)) # pick and size
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
zeros = torch.zeros(size=(224,224,3))
zeros.shape, zeros.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
ones = torch.ones(size=(2,3))

## Creating a range of tensors and tensors-like

In [ ]:
# torch.range(0,10) better not to use
ten_range = torch.arange(0,10)

In [ ]:
torch.arange(1000,0,-7) # start , stop , step

tensor([1000,  993,  986,  979,  972,  965,  958,  951,  944,  937,  930,  923,
         916,  909,  902,  895,  888,  881,  874,  867,  860,  853,  846,  839,
         832,  825,  818,  811,  804,  797,  790,  783,  776,  769,  762,  755,
         748,  741,  734,  727,  720,  713,  706,  699,  692,  685,  678,  671,
         664,  657,  650,  643,  636,  629,  622,  615,  608,  601,  594,  587,
         580,  573,  566,  559,  552,  545,  538,  531,  524,  517,  510,  503,
         496,  489,  482,  475,  468,  461,  454,  447,  440,  433,  426,  419,
         412,  405,  398,  391,  384,  377,  370,  363,  356,  349,  342,  335,
         328,  321,  314,  307,  300,  293,  286,  279,  272,  265,  258,  251,
         244,  237,  230,  223,  216,  209,  202,  195,  188,  181,  174,  167,
         160,  153,  146,  139,  132,  125,  118,  111,  104,   97,   90,   83,
          76,   69,   62,   55,   48,   41,   34,   27,   20,   13,    6])

In [ ]:
# Creating a tensor-like
ten_zeros = torch.zeros_like(input=ten_range)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
ten_ones = torch.ones_like(ten_range)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

## Tensor Data types

*Note:* The big 3 error in PyTorch deep learning
1. Tensors not in the right data type. `programming problem`
2. Tensors not in the right shape. `Linear Algebra problem`
3. Tensors not in the right device. `PyTorch problem`

In [ ]:
float_32_tensor = torch.tensor([1.0, 2.0, 3.0],
                               dtype = None, # torch.float32,16,64 or torch.int16,32,64 etc
                               device = None, # "cuda" or "cpu",  what device is your tensor on
                               requires_grad = False) # whether or not to track gradients with this tensors operations


torch.float32

In [ ]:
# default data type is float32, default device is 'cpu', default grad is False
float_32_tensor.dtype, float_32_tensor.device , float_32_tensor.requires_grad

(torch.float32, device(type='cpu'), False)

In [ ]:
torch.tensor([1,2,3],dtype=torch.bool) * torch.tensor([1,2,3],dtype=torch.float32)

tensor([1., 2., 3.])

In [ ]:
# torch.tensor([1,2,3],device = 'cpu') * torch.tensor([2,3,4], device='cuda') error

In [ ]:
test_tensor = torch.tensor([1,2,3],dtype=torch.float32)
test_tensor.device, test_tensor

(device(type='cpu'), tensor([1., 2., 3.]))

In [ ]:
test_tensor = test_tensor.to('cuda').requires_grad_(True) # change the device and grad after creating the tensor
test_tensor

tensor([1., 2., 3.], device='cuda:0', requires_grad=True)

## Manipulting Tensors (Tensors operations)

* additon ` + 10` element wise addition | ```tourch.add(tensor,10)``` | ```tensor.add(10)```
* subtraction ` - 10` element wise subtraction  ```tourch.sub(tensor,10)``` | ```tensor.sub(10)```
* multiplication (element-wise) ` * 10` |  ```tourch.mul(tensor,10)``` |  ```tensor.mul(10)```
* division ` / 10 ` |  ```tourch.div(tensor,10)``` |  ```tensor.div(10)```
* matrix multiplication

In [ ]:
t = torch.tensor([1,2,3])
torch.div(t,10)

tensor([0.1000, 0.2000, 0.3000])

In [ ]:
t.div(3)

tensor([0.3333, 0.6667, 1.0000])

### MATRIX multiplication

In [ ]:
A = torch.arange(1,10).reshape(3,3)
B = torch.arange(1,7).reshape(3,2)
A.shape,B.shape # you can perform A * B matmul


(torch.Size([3, 3]), torch.Size([3, 2]))

In [ ]:
torch.matmul(A,B) # or use torch.mm

tensor([[ 22,  28],
        [ 49,  64],
        [ 76, 100]])

In [ ]:
tensor = torch.arange(1,1000000)

In [ ]:
%%time
value = 0
for i in tensor:
  value += i*i
print(value)

tensor(333332833333500000)
CPU times: user 6.14 s, sys: 284 ms, total: 6.42 s
Wall time: 6.42 s


In [ ]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 1.56 ms, sys: 0 ns, total: 1.56 ms
Wall time: 1.56 ms


tensor(333332833333500000)

##Tensor Aggregation  (**min,max...etc**)

`torch.min(tensor), torch.max(tensor), torch.sum(tensor)` \\
`torch.mean(tensor)` **This need to be float or complex datatype**

`torch.argmin(), torch.argmax()` ** this is used to find the index of tha max or min value**

## Resahping, stacking, squeezing, unsqueesing tensors

* Reshaping : reshapes a tensor to defined shape.
* View : Return a view of a tensor of certain shape but keep the same memory as the original tensor.
* Stacking : concatenate multiple tensors `torch.hstack(), torch.vstack(), torch.stack()`
* Squeeze : removes all `1` dimensions from a tensor.
* Unsqueeze : add `1` dimenstio to a tensor.
* Permute : Return a view of the input with dimensions permuted (swapped) in certain way.

In [ ]:
import torch
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# reshape
reshaped_x = x.reshape(3,3) # 3,3 or 1,9 or 9,1 works for this matrix
reshaped_x

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [ ]:
view_x = x.view(3,3) # this return a copy of x without affecting the original tensor
view_x # changing view_x -> changing x, beacuase it's like object pointers but with different view

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [ ]:
x.view(3,3)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [ ]:
# stack tensors on top of each other
stacked_x = torch.stack([x,x,x,x],dim=0)
stacked_x

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
stacked_x = torch.stack([x,x,x,x],dim=1) # similar to previous example but stacked_x.T
stacked_x

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
x.unsqueeze(dim=0) , x.unsqueeze(dim=0).shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
x.unsqueeze(dim=1), x.unsqueeze(dim=1).shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
# permute : Return a view of the original tensor but with rearragning the dimensions in specified way
x_original = torch.rand(size=(224,224,3)) # [height, width, color_channles]

x_permuted = x_original.permute(2,0,1) # [color_channles, height, width]
x_original.shape, x_permuted.shape # remember they are sharing the same memroy object -> any changes on x_original or x_permuted will affect the other one

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

## Indexing (selecting data)

Indexing with PyTorch is similar to indexing with NumPy

In [ ]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape, x.ndim

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]),
 3)

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][0] , x[0][1], x[0][2] # == x[0,0] , x[0,1] , x[0,2]

(tensor([1, 2, 3]), tensor([4, 5, 6]), tensor([7, 8, 9]))

In [ ]:
x[0,0,0]

tensor(1)

In [ ]:
# Index to return 9
print(x[0,2,2])

# Index to return [3,6,9]
print(x[:,:,2])


tensor(9)
tensor([[3, 6, 9]])


## PyTorch and NumPy

* Data in NumPy to PyTorch -> `torch.from_numpy(ndarray)`
* PyTorch tenosr to NumPy -> `torch.Tensor.numpy()`

In [ ]:
import torch
import numpy as np

array = np.arange(1.0,10.0)
tensor = torch.from_numpy(array) # when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
print(array)
print(tensor)

[1. 2. 3. 4. 5. 6. 7. 8. 9.]
tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64)


In [ ]:
array = array + 1

In [ ]:
print(array)
print(tensor)

[ 2.  3.  4.  5.  6.  7.  8.  9. 10.]
tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64)


In [ ]:
tensor = torch.ones(7)
array = tensor.numpy() # or torch.Tensor.numpy(tensor)
array

array([1., 1., 1., 1., 1., 1., 1.], dtype=float32)